### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by alexmantaut** [alukach/aws-sam-typescript-boilerplate#4]
`yarn install` fails with the following message:

`
 ./webpack-cli/bin/config-yargs.js:89
 				describe: optionsSchema.definitions.output.properties.path.description,
 				                                           ^
 TypeError: Cannot read property 'properties' of undefined
`

**Comment by alexmantaut** [comment]
Added PR #3 to solve issue

**Comment by alukach** [comment]
Closed by #3
